AllCops:
  Exclude:
    # Ignore HTML related things
    - '**/*.erb'
    # Ignore vendored gems
    - 'vendor/**/*'
    # Ignore code from test fixtures
    - 'spec/fixtures/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false
